//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISharpConvertor.UIModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RssUserNewsModel
    {
        public int cId { get; set; }
        public int cIdUser { get; set; }
        public int cIdNews { get; set; }
     }
}
