//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISharpConvertor.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBank
    {
        public tbBank()
        {
            this.tbAdress = new HashSet<tbAdress>();
            this.tbComins = new HashSet<tbComins>();
            this.tbCurrencyRate = new HashSet<tbCurrencyRate>();
        }
    
        public int cId { get; set; }
        public string cName { get; set; }
        public int cRating { get; set; }
    
        public virtual ICollection<tbAdress> tbAdress { get; set; }
        public virtual ICollection<tbComins> tbComins { get; set; }
        public virtual ICollection<tbCurrencyRate> tbCurrencyRate { get; set; }
    }
}
