//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISharpConvertor.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbComins
    {
        public int cId { get; set; }
        public int cTopic { get; set; }
        public string cDecription { get; set; }
        public int cIdUser { get; set; }
        public int cIdBank { get; set; }
        public Nullable<int> cIdAdress { get; set; }
    
        public virtual tbAdress tbAdress { get; set; }
        public virtual tbBank tbBank { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
