//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISharpConvertor.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRate
    {
        public tbRate()
        {
            this.tbCurrencyRate = new HashSet<tbCurrencyRate>();
        }
    
        public int cId { get; set; }
        public double cRate { get; set; }
        public System.DateTime cDate { get; set; }
        public int cIsValid { get; set; }
        public string SellBuy { get; set; }
    
        public virtual ICollection<tbCurrencyRate> tbCurrencyRate { get; set; }
    }
}
