//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISharpConvertor.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRssUser
    {
        public tbRssUser()
        {
            this.tbRssUserNews = new HashSet<tbRssUserNews>();
        }
    
        public int cId { get; set; }
        public Nullable<int> cMail { get; set; }
    
        public virtual tbAdress tbAdress { get; set; }
        public virtual ICollection<tbRssUserNews> tbRssUserNews { get; set; }
    }
}
